package be.beneterwan.gestiongare.applicgare.dialogs;

import be.beneterwan.gestiongare.applicgare.ApplicGareFrame;
import be.beneterwan.gestiongare.commons.trains.HoraireTrain;
import be.beneterwan.gestiongare.commons.trains.Train;
import java.util.Set;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;

/**
 * @author bendem & Curlybear
 */
public class TrainListDialog extends JDialog {

    public TrainListDialog(ApplicGareFrame frame) {
        super(frame, "Liste des trains du jour", true);
        initComponents();

        // Loading train list
        Set<HoraireTrain> list = frame.getApplicGare().getHoraires();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Numero");
        model.addColumn("Wagons");
        model.addColumn("Origine");
        model.addColumn("Destination");
        model.addColumn("Arrivée");
        model.addColumn("Départ");
        for(HoraireTrain horaire : list) {
            Train train = horaire.getTrain();
            model.addRow(new Object[] {
                train.getType().name() + train.getNumero(),
                train.getWagons().size(),
                horaire.getOrigine(),
                horaire.getDestination(),
                String.format("%02d:%02d", horaire.getArrivee()/60, horaire.getArrivee()%60),
                String.format("%02d:%02d", horaire.getDepart()/60, horaire.getDepart()%60)
            });
        }
        trainList.setModel(model);

        setLocationRelativeTo(null);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trainList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        trainList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(trainList);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable trainList;
    // End of variables declaration//GEN-END:variables
}
