package be.beneterwan.gestiongare.users;

import be.beneterwan.gestiongare.applicgare.ApplicGareFrame;

/**
 *
 * @author Bear
 */
public class AddUserFrame extends javax.swing.JFrame {
    
    private final ApplicGareFrame parent;

    /**
     * Creates new form AddUserFrame
     */
    public AddUserFrame(ApplicGareFrame parent) {
        super("Nouvel utilisateur");
        initComponents();
        this.parent = parent;
        setLocationRelativeTo(null);
        pack();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldNomUser = new javax.swing.JTextField();
        checkBoxAdmin = new javax.swing.JCheckBox();
        labelNomUser = new javax.swing.JLabel();
        labelMdP1 = new javax.swing.JLabel();
        labelAdmin = new javax.swing.JLabel();
        buttonConfirmer = new javax.swing.JButton();
        buttonAnnuler = new javax.swing.JButton();
        labelMdP2 = new javax.swing.JLabel();
        passwordFieldMdP1 = new javax.swing.JPasswordField();
        passwordFieldMdP2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNomUser.setText("Nom de l'utilisateur :");

        labelMdP1.setText("Mot de passe de l'utilisateur :");

        labelAdmin.setText("Administrateur? :");

        buttonConfirmer.setText("Confirmer");

        buttonAnnuler.setText("Annuler");

        labelMdP2.setText("Confirmer le mot de passe :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(buttonConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNomUser)
                    .addComponent(labelMdP1)
                    .addComponent(labelAdmin)
                    .addComponent(labelMdP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkBoxAdmin)
                    .addComponent(textFieldNomUser)
                    .addComponent(passwordFieldMdP2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(passwordFieldMdP1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMdP1)
                    .addComponent(passwordFieldMdP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMdP2)
                    .addComponent(passwordFieldMdP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxAdmin)
                    .addComponent(labelAdmin))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirmer)
                    .addComponent(buttonAnnuler))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnnuler;
    private javax.swing.JButton buttonConfirmer;
    private javax.swing.JCheckBox checkBoxAdmin;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JLabel labelMdP1;
    private javax.swing.JLabel labelMdP2;
    private javax.swing.JLabel labelNomUser;
    private javax.swing.JPasswordField passwordFieldMdP1;
    private javax.swing.JPasswordField passwordFieldMdP2;
    private javax.swing.JTextField textFieldNomUser;
    // End of variables declaration//GEN-END:variables
}
