package be.beneterwan.gestiongare.applicgare;

import javax.swing.JFrame;

/**
 * @author bendem
 */
public class ApplicGareFrame extends JFrame {

    /**
     * Creates new form ApplicGareFrame
     */
    public ApplicGareFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nextTrainPanel = new javax.swing.JPanel();
        notifyButtonsPanel = new javax.swing.JPanel();
        answerPanel = new javax.swing.JPanel();
        railwayOccupationTablePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 1));

        topPanel.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setText("Responsable gare");
        topPanel.add(jLabel1);

        jLabel2.setText("Image");
        topPanel.add(jLabel2);

        getContentPane().add(topPanel);

        nextTrainPanel.setLayout(new java.awt.GridLayout());
        getContentPane().add(nextTrainPanel);

        notifyButtonsPanel.setLayout(new java.awt.GridLayout());
        getContentPane().add(notifyButtonsPanel);

        answerPanel.setLayout(new java.awt.GridLayout());
        getContentPane().add(answerPanel);

        railwayOccupationTablePanel.setLayout(new java.awt.GridLayout());
        getContentPane().add(railwayOccupationTablePanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicGareFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch(InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicGareFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch(IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicGareFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch(javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicGareFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicGareFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel answerPanel;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JPanel nextTrainPanel;
    protected javax.swing.JPanel notifyButtonsPanel;
    protected javax.swing.JPanel railwayOccupationTablePanel;
    protected javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
